version: '3'

tasks:
  test:
    cmds:
      - go test ./...

  run:example:quickstart:
    desc: Run the quickstart example
    cmds:
      - go run -tags=examples ./examples/quickstart/main.go

  run:example:static:
    desc: Run the static file serving example
    cmds:
      - go run -tags=examples ./examples/static/main.go

  run:example:builder:
    desc: Run the builder pattern example (advanced middleware and routing)
    cmds:
      - go run -tags=examples ./examples/builder-pattern/main.go
